# Generated by Django 5.1.1 on 2024-09-19 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='예약 고유번호')),
                ('start_date', models.DateTimeField(verbose_name='시험 시작일시')),
                ('end_date', models.DateTimeField(verbose_name='시험 종료일시')),
                ('participants', models.PositiveIntegerField(verbose_name='응시인원')),
                ('status', models.IntegerField(choices=[(1, '대기중'), (2, '확정됨'), (3, '거부됨'), (4, '삭제됨')], default=1, verbose_name='예약 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservation',
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='reservation_start_d_ce8013_idx'), models.Index(fields=['created_at'], name='reservation_created_295dea_idx'), models.Index(fields=['updated_at'], name='reservation_updated_792e80_idx')],
            },
        ),
    ]
